config/routes.rb
Rails.application.routes.draw do
  config = Rails.application.config.esthe

  constraints host: config[:staff][:host] do
    namespace :staff ,path: config[:staff][:path] do
      root 'top#index'
      get 'login' => 'sessions#new', as: :login

      resource :session, only:[ :create, :destroy]

      resource :account

      resource :password, only: [ :show, :edit, :update]

      resources :customers

      resources :customers ,only: [:index] do
         member { get :print}
      end

        resources :companies do
        resources :companies, only: [:index]
      end

      resources :loanorders

      resources 'loanorders', only: [:index] do
        collection { post :import }
      end

      resources :import_logs, only: [:index]

    end
  end

  constraints host: config[:customer][:host] do
    namespace :customer ,path: config[:customer][:path] do

      get 'login' => 'sessions#new', as: :login
      get 'session' => 'sessions#destroy'
      resource :session, only: [ :create, :destroy]

      resource :customer do
        patch :confirm
      end

      resources :loanorders, only:[ :index]

      resources :loanorders, only:[ :index] do
        collection { get :search}
      end

      resource :password,only: [:show, :edit, :update]
    end
  end

  constraints host: config[:admin][:host] do
    namespace :admin , path: config[:admin][:path] do
      root 'top#index'
      get 'login' => 'sessions#new', as: :login
      post 'session' => 'sessions#create', as: :session
      delete 'session' => 'sessions#destroy'
      resource :session, only:[ :create, :destroy]
      get 'customers/update_stores', as: 'update_stores'

      resources :staff_members do
        resources :staff_events, only: [:index]
      end
      resources :staff_events, only: [:index]

      resources :customers

      resources :customers ,only: [:index] do
         member { get :print}
      end

      resources :companies do
        resources :companies, only: [:index]
      end

      resources :loanorders

      resources 'loanorders', only: :index do
            collection { post :import }
      end

      resources :import_logs, only: [:index]
    end
  end

    root 'errors#not_found'

    get '*anything' => 'errors#not_found'

    

end

app/models/company.rb
class Company < ActiveRecord::Base
		has_many :customers, dependent: :destroy
		validates :company_code, :company_name, presence: true
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::Base

  def index
    @companies = Company.order(:company_code)
    @companies = @companies.page(params[:page])
  end

  def show
    company = Company.find(params[:id])
    redirect_to [ :edit, :admin, company ]
  end

  def new
    @company = Company.new
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash.notice = '加盟店を新規登録しました。'
      redirect_to :admin_companies
    else
      render action: 'new'
    end
  end

  def update
    @company = Company.find(params[:id])
    @company.assign_attributes(company_params)
    if @company.valid?
	    if @company.save
	      flash.notice = '加盟店を更新しました。'
	      redirect_to :admin_companies
	    else
	      render action: 'edit'
	    end
	   else
	   	render action: 'edit'
	   end
  end

  def destroy
    company = Company.find(params[:id])
    company.destroy!
    flash.notice = '加盟店を削除しました。'
    redirect_to :admin_companies
  end
  private

  def company_params
  	params.require(:company).permit(
  		:company_code, :company_name)
  end
end

app/controllers/staff/companies_controller.rb
class Staff::CompaniesController < Staff::Base

  def index
    @companies = Company.order(:company_code)
    @companies = @companies.page(params[:page])
  end

  def show
    company = Company.find(params[:id])
    redirect_to [ :edit, :admin, company ]
  end

  def new
    @company = Company.new
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash.notice = '加盟店を新規登録しました。'
      redirect_to :staff_companies
    else
      render action: 'new'
    end
  end

  def update
    @company = Company.find(params[:id])
    @company.assign_attributes(company_params)
    if @company.valid?
	    if @company.save
	      flash.notice = '加盟店を更新しました。'
	      redirect_to :staff_companies
	    else
	      render action: 'edit'
	    end
	   else
	   	render action: 'edit'
	   end
  end

  def destroy
    company = Company.find(params[:id])
    company.destroy!
    flash.notice = '加盟店を削除しました。'
    redirect_to :staff_companies
  end
  private

  def company_params
  	params.require(:company).permit(
  		:company_code, :company_name)
  end
end

app/views/admin/companies/_form.html.erb
<%= markup do |m|
  p = CustomerFormPresenter.new(f, self)
  m << p.notes

  m << p.text_field_block(:company_code, '加盟店コード', size: 4, required: true)
  m << p.text_field_block(:company_name, '加盟店名', size: 60, required: true)

end %>

app/views/admin/companies/edit.html.erb
<% @title = '加盟店情報の編集' %>
<h1><%= @title %></h1>

<div id="generic-form">
  <%= form_for [ :admin, @company ] do |f| %>
    <%= render 'form', f: f %>
    <div class="buttons" style="text-align:center;">
      <%= f.submit '更新',id:"edit_submit" %>
      <%= link_to 'キャンセル', :admin_companies,id:"edit_cancel" %>
    </div>
  <% end %>
</div>

app/views/admin/companies/index.html.erb
<% @title = '加盟店一覧' %>
<h1><%= @title %></h1>

<div class="table-wrapper">

  <div class="links_narrow">
    <%= link_to '新規登録', :new_admin_company %>
  </div>

  <%= paginate @companies %>

  <table class="listing_narrow">
    <tr>
      <th>加盟店コード</th>
      <th>加盟店名</th>
      <th>アクション</th>
    </tr>
    <% @companies.each do |m| %>
      <% p = CustomerPresenter.new(m, self) %>
      <tr>
        <td width="100px" style="text-align:center;"><%= m.company_code %></td>
        <td><%= m.company_name %></td>

        <td class="actions">
          <%= link_to '編集', [ :edit, :admin, m ] %> |
          <%= link_to '削除', [ :admin, m ], method: :delete,
            data: { confirm: '本当に削除しますか？' } %>
        </td>
      </tr>
    <% end %>
  </table>

  <%= paginate @companies %>

  <div class="links_narrow">
    <%= link_to '新規登録', :new_admin_company %>
  </div>

</div>

app/views/admin/companies/new.html.erb
<% @title = '加盟店の新規登録' %>
<h1><%= @title %></h1>

<div id="generic-form">
  <%= form_for @company ,url: admin_companies_path do |f| %>
    <%= render 'form', f: f %>
    <div class="buttons" style="text-align:center;">
      <%= f.submit '登録' ,id:"edit_submit" %>
      <%= link_to 'キャンセル', :admin_companies ,id:"edit_cancel" %>
    </div>
  <% end %>
</div>