config/routes.rb
Rails.application.routes.draw do
  config = Rails.application.config.esthe

  constraints host: config[:staff][:host] do
    namespace :staff ,path: config[:staff][:path] do
      root 'top#index'
      get 'login' => 'sessions#new', as: :login

      resource :session, only:[ :create, :destroy]

      resource :account

      resource :password, only: [ :show, :edit, :update]

      resources :customers

      resources :customers ,only: [:index] do
         member { get :print}
      end

        resources :companies do
        resources :companies, only: [:index]
      end

      resources :loanorders

      resources 'loanorders', only: [:index] do
        collection { post :import }
      end

      resources :import_logs, only: [:index]

    end
  end

  constraints host: config[:customer][:host] do
    namespace :customer ,path: config[:customer][:path] do

      get 'login' => 'sessions#new', as: :login
      get 'session' => 'sessions#destroy'
      resource :session, only: [ :create, :destroy]

      resource :customer do
        patch :confirm
      end

      resources :loanorders, only:[ :index]

      resources :loanorders, only:[ :index] do
        collection { get :search}
      end

      resource :password,only: [:show, :edit, :update]
    end
  end

  constraints host: config[:admin][:host] do
    namespace :admin , path: config[:admin][:path] do
      root 'top#index'
      get 'login' => 'sessions#new', as: :login
      post 'session' => 'sessions#create', as: :session
      delete 'session' => 'sessions#destroy'
      resource :session, only:[ :create, :destroy]
      get 'customers/update_stores', as: 'update_stores'

      resources :staff_members do
        resources :staff_events, only: [:index]
      end
      resources :staff_events, only: [:index]

      resources :customers

      resources :customers ,only: [:index] do
         member { get :print}
      end

      resources :companies do
        resources :companies, only: [:index]
      end

      resources :loanorders

      resources 'loanorders', only: :index do
            collection { post :import }
      end

      resources :import_logs, only: [:index]
    end
  end

    root 'errors#not_found'

    get '*anything' => 'errors#not_found'

    

end

app/models/staff_member.rb
class StaffMember < ActiveRecord::Base

	include EmailHolder
	include StaffPersonalNameHolder

	has_many :events, class_name: 'StaffEvent', dependent: :destroy

	#has_many :orders, class_name: 'Loanorder', dependent: :destroy

	#before_validation do
	#	self.email_for_index = email.downcase if email
	#end	

	validates :email, presence: true

	validates :start_date, presence: true, date: {
    after_or_equal_to: Date.new(2015, 1, 1),
    before: ->(obj) { 1.year.from_now.to_date },
    allow_blank: true
  }
  validates :end_date, date: {
    after: :start_date,
    before: ->(obj) { 1.year.from_now.to_date },
    allow_blank: true
  }





	#validates :password, presence: true
   #     length:     {within: 6..30}

  has_secure_password


	#def password=(raw_password)
	#	#self[:password] = raw_password
	#	if raw_password.kind_of?(String)
	#		self.hashed_password = BCrypt:: Password.create(raw_password)
	#	elsif raw_password.nil?
	#		self.hashed_password = nil
	#	end
	#end

	def active?
		!suspended? && start_date <= Date.today &&
		(end_date.nil? || end_date > Date.today)
	end
end

app/controllers/admin/staff_members_controller.rb
class Admin::StaffMembersController < Admin::Base

  def index
    @staff_members = StaffMember.order(:family_name_kana, :given_name_kana)
    @staff_members = @staff_members.page(params[:page]).per(12)
  end

  def show
    staff_member = StaffMember.find(params[:id])
    redirect_to [ :edit, :admin, staff_member ]
  end

  def new
    @staff_member = StaffMember.new
  end

  def edit
    @staff_member = StaffMember.find(params[:id])
  end

  def create
    @staff_member = StaffMember.new(staff_member_params)
    if @staff_member.save
      flash.notice = 'システム担当者情報を新規登録しました。'
      redirect_to :admin_staff_members
    else
      render action: 'new'
    end
  end

  def update
    @staff_member = StaffMember.find(params[:id])
    @staff_member.assign_attributes(staff_member_params)
    if @staff_member.valid?
	    if @staff_member.save
	      flash.notice = 'システム担当者情報を更新しました。'
	      redirect_to :admin_staff_members
	    else
	      render action: 'edit'
	    end
	   else
	   	render action: 'edit'
	   end
  end

  def destroy
    staff_member = StaffMember.find(params[:id])
    staff_member.destroy!
    flash.notice = 'システム担当者情報を削除しました。'
    redirect_to :admin_staff_members
  end
  private

  def staff_member_params
  	params.require(:staff_member).permit(
  		:email, :password, :family_name, :given_name,
  		:family_name_kana, :given_name_kana,
  		:start_date, :end_date, :suspended
  		)
  end
end

app/views/admin/staff_members/_form.html.erb
<%= markup do |m|
  p = StaffMemberFormPresenter.new(f, self)
  m << p.notes
  p.with_options(required: true) do |q|
    m << q.text_field_block(:email, 'メールアドレス', size: 32)
    m << q.password_field_block(:password, 'パスワード', size: 32)
    m << q.full_name_block(:family_name, :given_name, '氏名')
    m << q.full_name_block(:family_name_kana, :given_name_kana, 'フリガナ')
    m << q.date_field_block(:start_date, '開始日')
    m << q.date_field_block(:end_date, '終了日', required: false)
  end
  m << p.check_boxes
end %>

app/views/admin/staff_members/edit.html.erb
<% @title = 'システム担当者の編集' %>
<h1><%= @title %></h1>

<div id="generic-form">
  <%= form_for [ :admin, @staff_member ] do |f| %>
    <%= render 'form', f: f %>
    <div class="buttons" style="text-align:center;">
      <%= f.submit '更新',id:"edit_submit" %>
      <%= link_to 'キャンセル',:admin_staff_members,id:"edit_cancel" %>
    </div>
  <% end %>
</div>

app/views/admin/staff_members/index.html.erb
<% @title = 'システム担当者管理' %>
<h1><%= @title %></h1>

<div class="table-wrapper">
  <div class="links">
    <%= link_to '新規登録', :new_admin_staff_member %>
  </div>

  <%= paginate @staff_members %>

  <table class="listing">
    <tr>
      <th>氏名</th>
      <th>フリガナ</th>
      <th>メールアドレス</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>停止フラグ</th>
      <th>アクション</th>
    </tr>
    <% @staff_members.each do |m| %>
      <% p = StaffMemberPresenter.new(m, self) %>
      <tr>
        <td><%= m.family_name %> <%= m.given_name %></td>
        <td><%= m.family_name_kana %> <%= m.given_name_kana %></td>
        <td class="email"><%= m.email %></td>
        <td class="date"><%= m.start_date.strftime('%Y/%m/%d') %></td>
        <td class="date"><%= m.end_date.try(:strftime, '%Y/%m/%d') %></td>
        <td class="boolean"><%= p.suspended_mark %></td>
        <td class="actions">
          <%= link_to '編集', [ :edit, :admin, m ] %> |
          <%= link_to 'Events', [ :admin, m, :staff_events ] %> |
          <%= link_to '削除', [ :admin, m ], method: :delete,
            data: { confirm: '本当に削除しますか？' } %>
        </td>
      </tr>
    <% end %>
  </table>

  <%= paginate @staff_members %>

  <div class="links">
    <%= link_to '新規登録', :new_admin_staff_member %>
  </div>
</div>

app/views/admin/staff_members/new.html.erb
<% @title = 'システム担当者の新規登録' %>
<h1><%= @title %></h1>

<div id="generic-form">
  <%= form_for @staff_member ,url: admin_staff_members_path do |f| %>
    <%= render 'form', f: f %>
    <div class="buttons" style="text-align:center;">
      <%= f.submit '登録' ,id:"edit_submit" %>
      <%= link_to 'キャンセル', :admin_staff_members ,id:"edit_cancel" %>
    </div>
  <% end %>
</div>