config/routes.rb
Rails.application.routes.draw do
  config = Rails.application.config.esthe

  constraints host: config[:staff][:host] do
    namespace :staff ,path: config[:staff][:path] do
      root 'top#index'
      get 'login' => 'sessions#new', as: :login

      resource :session, only:[ :create, :destroy]

      resource :account

      resource :password, only: [ :show, :edit, :update]

      resources :customers

      resources :customers ,only: [:index] do
         member { get :print}
      end

        resources :companies do
        resources :companies, only: [:index]
      end

      resources :loanorders

      resources 'loanorders', only: [:index] do
        collection { post :import }
      end

      resources :import_logs, only: [:index]

    end
  end

  constraints host: config[:customer][:host] do
    namespace :customer ,path: config[:customer][:path] do

      get 'login' => 'sessions#new', as: :login
      get 'session' => 'sessions#destroy'
      resource :session, only: [ :create, :destroy]

      resource :customer do
        patch :confirm
      end

      resources :loanorders, only:[ :index]

      resources :loanorders, only:[ :index] do
        collection { get :search}
      end

      resource :password,only: [:show, :edit, :update]
    end
  end

  constraints host: config[:admin][:host] do
    namespace :admin , path: config[:admin][:path] do
      root 'top#index'
      get 'login' => 'sessions#new', as: :login
      post 'session' => 'sessions#create', as: :session
      delete 'session' => 'sessions#destroy'
      resource :session, only:[ :create, :destroy]
      get 'customers/update_stores', as: 'update_stores'

      resources :staff_members do
        resources :staff_events, only: [:index]
      end
      resources :staff_events, only: [:index]

      resources :customers

      resources :customers ,only: [:index] do
         member { get :print}
      end

      resources :companies do
        resources :companies, only: [:index]
      end

      resources :loanorders

      resources 'loanorders', only: :index do
            collection { post :import }
      end

      resources :import_logs, only: [:index]
    end
  end

    root 'errors#not_found'

    get '*anything' => 'errors#not_found'

    

end

app/models/loanorder.rb
class Loanorder < ActiveRecord::Base
	#self.inheritance_column = nil

	#belongs_to :member, class_name: 'StaffMember', foreign_key: 'staff_member_id'

	#belongs_to :customer, class_name: 'Customer', foreign_key: 'customer_id'

  def self.import(file)
      @file = file.path
      #受付日が１年以上前のデータは削除
      #Loanorder.where('reciept_date < ?',1.years.ago.to_date).delete_all()
      CSV.foreach(file.path, headers: true) do |row|
        # 売上NO(row(1)が見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
        if row[0] == '9'
          order = find_by(sales_no: row[1],company_code: row[2],store_code: row[5])
          if order != nil
            order.destroy!
          end
        else
          #row[15] = DateTime.parse(row[15])
          order = find_by(sales_no: row[1],company_code: row[2],store_code: row[5]) || new
          # CSVからデータを取得し、設定する
          order.attributes = row.to_hash.slice(*updatable_attributes)
          # 保存する
          order.save!
        end
      end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["update_flg","sales_no","company_code","company_name","order_date","store_code","store_name","loan_company_name","receipt_number","area","application_money","user_name","old_status","status","charge_date","update_datetime"]
  end
end

app/controllers/admin/loanorders_controller.rb
class Admin::LoanordersController < Admin::Base
	require 'date'
	def index
		#@search_form = Admin::LoanorderSearchForm.new
		@max = Loanorder.maximum(:update_datetime)
  	@loan = Loanorder.select(:company_code,:company_name).uniq
  	#@loanorders = @loanorders.page(params[:page])
  	@search_form = Admin::LoanorderSearchForm.new(params[:search])
  	@loanorders = @search_form.search.page(params[:page]).per(30)
  end

  def import
  # fileはtmpに自動で一時保存される
	  if params[:file].blank?
			redirect_to admin_loanorders_url, notice: "ファイルを選択してください。"	
		else
			file_name = params[:file].original_filename
	  	Loanorder.import(params[:file])
	  	ImportLog.create!(email: session[:email], import_datetime: DateTime.now, import_filename: file_name)
	  	#import_logs.create!(email: session[email], import_time: Current.time, import_filename: params[:file])
		  redirect_to admin_loanorders_url, notice: "申込データを更新しました。"
		end
	end
end

app/controllers/customer/loanorders_controller.rb
class Customer::LoanordersController < Customer::Base
	def index
		@max = Loanorder.maximum(:update_datetime)
		@customer = Customer.where(company_id: session[:company_code])
		@company_code = session[ :company_code]
		#2015/10/24 店舗での絞り込みをもらしていた
		#ActiveModelに店舗コードを渡すため、search_formの引数を追加
		@store_code   = session[ :store_code].to_s	
		if session[:parent_and_child] == '親'  then
			@search_form = Customer::LoanorderSearchForm.new(params[:search])
			@loanorders = @search_form.search(session[ :company_code],session[ :store_code],'1').page(params[:page]).per(14)
			@total = @search_form.search(session[ :company_code],session[ :store_code],'1').group(:company_id).sum(:application_money)
		else
			@search_form = Customer::LoanorderSearchForm.new(params[:search])
			@loanorders = @search_form.search(session[ :company_code],@store_code,'2').page(params[:page]).per(14)
			@total = @search_form.search(session[ :company_code],@store_code,'2').group(:company_id).sum(:application_money)
		end
	end
end

app/controllers/staff/loanorders_controller.rb
class Staff::LoanordersController < Staff::Base
	require 'date'
	def index
		#@search_form = Admin::LoanorderSearchForm.new
		@max  = Loanorder.maximum(:update_datetime)
  	@loan = Loanorder.select(:company_code,:company_name).uniq
  	#@loanorders = @loanorders.page(params[:page])
  	@search_form = Staff::LoanorderSearchForm.new(params[:search])
  	@loanorders = @search_form.search.page(params[:page]).per(30)
  end

  def import
  # fileはtmpに自動で一時保存される
	  if params[:file].blank?
			redirect_to staff_loanorders_url, notice: "ファイルを選択してください。"	
		else
			file_name = params[:file].original_filename
	  	Loanorder.import(params[:file])
	  	ImportLog.create!(email: session[:email], import_datetime: DateTime.now, import_filename: file_name)
		  redirect_to staff_loanorders_url, notice: "顧客データを追加しました。"
		end
	end
end

app/views/admin/loanorders/_loanorder.html.erb
<option value="<%= loanorder.store_code %>"><%=  loanorder.store_name %></option>

app/views/admin/loanorders/_search_form.html.erb
<%= form_for @search_form, as: 'search', url: :admin_loanorders,
	html: { method: :get,class: "search"} do |f| %>

	<%= f.collection_select :company_code, Loanorder.select(:company_code, :company_name).uniq, :company_code, :company_name,include_blank: true %>

	 <%= f.submit '検索' %>


<% end %>

app/views/admin/loanorders/index.html.erb
<h1>申込データ一覧</h1>

<div class="table-wrapper">

<%= render 'search_form' %>
<%= paginate @loanorders %>
<div id="update-datetime"><p>最終更新日：<%= @max.strftime("%Y年%m月%d日 %H時%M分%S秒")%></p></div>
<table class="listing">
  <thead>
    <tr>
      <th>申込日</th>
      <th colspan="2">加　盟　店</th>
      <th colspan="2",width="50px">店　　舗</th>

      <th>信販会社名</th>
      <th>受付番号</th>
      <th>申込金額</th>
      <th>氏　　　名</th>
      <th>状　　　　　況</th>
      <th>入 金 日</th>
    </tr>
  </thead>

  <tbody>
    <% @loanorders.each do |loanorder| %>
      <tr>
        <td style="text-align:center;"><%= loanorder.order_date %></td>
        <td style="text-align:center;"><%= loanorder.company_code %></td>
        <td><%= loanorder.company_name %></td>
        <td style="text-align:center;"><%= loanorder.store_code %></td>
        <td><%= loanorder.store_name %></td>
        <td><%= loanorder.loan_company_name %></td>
        <td style="text-align:center;"><%= loanorder.receipt_number %></td>
        <td style="text-align:right;"><%= number_with_delimiter(loanorder.application_money) %></td>
        <td><%= loanorder.user_name %></td>
        <td><%= loanorder.status %></td>
        <td style="text-align:center;"><%= loanorder.charge_date %></td>
      </tr>
    <% end %>
  </tbody>

</table>
  <%= paginate @loanorders %>

<!-- ページの一番下に追加 -->
<%= form_tag import_admin_loanorders_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>

  </div>
<% end %>